name: gigapose
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip==23
  - python=3.9.6
  - pip:
    - pandas
    - blenderproc
    - bokeh
    - distinctipy
    - einops
    - ffmpeg
    - fvcore
    - gdown
    - hydra-colorlog
    - hydra-core
    - iopath
    - joblib==1.4.2
    - matplotlib
    - nvisii==1.1.72
    - omegaconf
    - onnx
    - onnxruntime
    - open3d==0.19.0
    - opencv-python
    - peft==0.14.0
    - pinocchio==0.4.3
    - pycocotools
    - pypng==0.20220715.0
    - pyrender
    - pyrr==0.10.3
    - pytorch-lightning==1.8.1
    - roma==1.5.1
    - ruamel.yaml
    - scikit-image==0.24.0
    - scipy
    - seaborn==0.13.2
    - simplejson==3.19.3
    - torch
    - torchmetrics==0.10.3
    - torchvision
    - transforms3d==0.4.2
    - wandb
    - webdataset==0.2.100
    - xatlas==0.0.9
    - xformers==0.0.18